development:
  adapter: postgresql
  database: upwave_dev
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: upwave_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: upwave_pro
  pool: 5
  timeout: 5000